[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "pip install -r requirements.txt"
]

[start]
cmd = "python server.py"
