[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","python"]}
buildEnvironment = "V2"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python server.py"
sleepApplication = true
multiRegionConfig = {"us-west1":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
