[build]
builder = "NIXPACKS"
buildEnvironment = "V2"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python server.py"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig.us-west1]
numReplicas = 1
